const usernames = [
    "xtourmaline",
    "frontear",
    `jenny_lee`,
    `mariofan64`,
    `zelda_rocks`,
    `ryan_wong`,
    `lara_croft`,
    `xavier_12`,
    `sonic_speed`,
    `kelly_tan`,
    `anna_smith`,
    `link_hero`,
    `samus_aran`,
    `tom_chen`,
    `peach_princess`,
    `max_power`,
    `kratos_god`,
    `luigi_bro`,
    `jack_jones`,
    `yoshi_egg`,
];

const domains = [
    `gmail.com`,
    `outlook.com`,
    `yahoo.com`,
    `icloud.com`,
    `protonmail.com`,
    `aol.com`,
    `hotmail.com`,
    `zoho.com`,
    `yandex.com`,
    `mail.com`,
]

const thoughts = [
    `Just finished watching Squid Game. Wow. Just wow. #mindblown`,
    `Happy birthday to my best friend and partner in crime. You are the peanut butter to my jelly, the cheese to my macaroni, and the gin to my tonic. Love you to the moon and back. 🎂🎉🎁`,
    `Nothing like a good book and a cup of coffee on a rainy day. #bookworm #cozyvibes`,
    `I'm so proud of myself for completing the 30-day yoga challenge. I feel stronger, more flexible, and more balanced. Namaste. 🙏 #yogaeverydamnday`,
    `Throwback to the time I met my celebrity crush. He was so nice and charming. And those eyes... 😍 #fangirlmoment #dreamcometrue`,
    `I can't believe I finally got my driver's license. Watch out world, here I come. #roadtrip #freedom`,
    `Today I learned that pineapple does not belong on pizza. It's a crime against humanity. #sorrynotsorry #pineapplepizzaiswrong`,
    `I just got the best news ever. I got accepted into my dream college. I'm so excited and grateful. #classof2028 #futuredoctor`,
    `I just baked the most delicious chocolate chip cookies ever. They are soft, chewy, and loaded with chocolate. Who wants one? #bakingqueen #cookiesfordays`,
    `I just witnessed the most amazing sunset ever. The sky was on fire with orange, pink, and purple hues. It was breathtaking. #nofilter #natureisbeautiful`,
    `I just voted. Did you? #vote #makeyourvoiceheard`,
    `I just got a new tattoo. It's a quote from my favorite book. It says "Don't let the muggles get you down." #harrypotterfan #inked`,
    `I just adopted the cutest puppy ever. His name is Milo and he is a golden retriever. He loves to play, cuddle, and chew on everything. #puppylove #dogmom`,
    `I just ran my first marathon. It was hard, but I did it. I'm so proud of myself. #runner #marathoner`,
    `I just won the lottery. I'm not kidding. I'm rich. #bestdayever #luckyme`,
    `I just got engaged. He proposed to me at the Eiffel Tower. It was so romantic. I said yes, of course. #engaged #heputaringonit`,
    `I just quit my job. I'm done with the corporate rat race. I'm going to travel the world and follow my passion. #quitmyjob #livemydream`,
    `I just dyed my hair pink. I love it. It's so fun and funky. #pinkhairdontcare #newlook`,
    `I just had the best burger ever. It was juicy, cheesy, and loaded with bacon. #burger #foodcoma`,
    `I just met the love of my life. He is smart, funny, and handsome. He also loves cats. #soulmate #meow`,
    `I just got a promotion. I'm now the manager of my department. I'm so happy and proud. #bossbabe #careergoals`,
    `I just had the worst day ever. Everything went wrong. I spilled coffee on my shirt, missed the bus, got yelled at by my boss, and lost my wallet. #worstdayever #needahug`,
    `I just watched the latest episode of Game of Thrones. I'm speechless. I can't believe what happened. #gameofthrones #shook`,
    `I just got a new phone. It's the latest model. It has a huge screen, a great camera, and a lot of cool features. #phoneupgrade #techsavvy`,
    `I just got back from an amazing trip to Hawaii. It was paradise. I swam with dolphins, hiked to a waterfall, and relaxed on the beach. #hawaii #paradise`,
    `I just graduated from high school. I'm so happy and proud. I can't wait to start the next chapter of my life. #graduation #classof2024`,
    `I just bought a new car. It's a red convertible. It's so fast and sleek. #newcar #vroomvroom`,
    `I just got a haircut. I chopped off 10 inches. It feels so light and fresh. #newhair #shorthairdontcare`,
    `I just made a new friend. He is a squirrel. He likes to eat nuts and climb trees. #squirrelfriend #nutsaboutyou`,
    `I just learned a new skill. I can juggle. It's so fun and challenging. #juggle #circus`,
    `I just had a baby. He is the most beautiful thing I've ever seen. He has my eyes and his father's nose. #babyboy #bundleofjoy`,
    `I just got a new piercing. It's on my nose. It hurts a little, but it looks cool. #pierced #nosey`,
    `I just watched a scary movie. It was terrifying. I screamed, jumped, and hid under the blanket. #scarymovie #nightmare`,
    `I just ate a whole pizza by myself. It was delicious. I regret nothing. #pizza #noregrets`,
    `I just went to a concert. It was awesome. I saw my favorite band live. They rocked the stage. #concert #rockon`,
    `I just got a new plant. It's a succulent. It's so cute and easy to take care of. #plantmom #succulent`,
    `I just got a new pair of shoes. They are so pretty and comfortable. They match with everything. #shoes #shoelover`,
    `I just read a great book. It was a thriller. It kept me on the edge of my seat. #booklover #thriller`,
    `I just went to the zoo. It was fun. I saw a lot of animals. My favorite was the panda. #zoo #panda`,
    `I just got a new tattoo. It's a butterfly. It symbolizes transformation and freedom. #tattoo #butterfly`,
    `I just got a new roommate. He is a ghost. He likes to haunt the house and make noises. #roommate #ghost`,
    `I just got a new hobby. I started knitting. It's relaxing and rewarding. I made a scarf. #knitting #scarf`,
    `I just got a new guitar. It's acoustic. It sounds beautiful. I'm learning how to play. #guitar #music`,
    `I just got a new pet. It's a hamster. He is fluffy and adorable. He likes to run on his wheel. #pet #hamster`,
    `I just got a new bike. It's green. It's fast and smooth. I love riding it. #bike #green`,
    `I just got a new dress. It's blue. It's elegant and flattering. I feel like a princess. #dress #blue`,
    `I just got a new hat. It's a fedora. It's stylish and cool. I look like a detective. #hat #fedora`,
    `I just got a new necklace. It's a locket. It has a picture of my grandmother. She gave it to me before she passed away. #necklace #locket`,
    `I just got a new mug. It's a unicorn. It's colorful and magical. It makes me happy. #mug #unicorn`,
    `I just got a new pillow. It's a emoji. It's yellow and smiley. It's soft and cuddly. #pillow #emoji`,
];

module.exports = { usernames, domains, thoughts };